#!/bin/bash
# settings v260421.26 | 2026-04-21 12:34:52
# post-change-summary.sh
# PostToolUse hook on Bash — fires when command includes git commit, git push, or clasp push.
# Reports:
#   - All affected files + current version stamp
#   - Git push: success/failure with repo name (github.com/user/repo)
#   - Clasp push: success/failure with GAS project name + short scriptId

input=$(cat)
cmd=$(echo "$input" | jq -r '.tool_input.command // ""')

# ── STOP MODE: called from Stop hook (no Bash command) ───────────────────────
# Auto-commits and pushes any uncommitted tracked changes.
if [ -z "$cmd" ]; then
  REPO="$HOME/claude"
  uncommitted=$(git -C "$REPO" status --porcelain 2>/dev/null | grep -v '^??')
  [ -z "$uncommitted" ] && exit 0

  GAS_NAMES="Code.gs Sidebar.html Sidebar-js.html Sidebar-css.html SheetAssistPanel.html UserGuide.html Tests.gs"
  file_lines=""
  gas_changed=0
  gas_project_dir=""

  while IFS= read -r line; do
    [ -z "$line" ] && continue
    rel="${line:3}"
    full="$REPO/$rel"
    fname=$(basename "$rel")
    [ -f "$full" ] || continue

    line1=$(head -1 "$full" 2>/dev/null)
    if echo "$line1" | grep -q '^#!'; then
      stamp_line=$(sed -n '2p' "$full" 2>/dev/null)
    else
      stamp_line="$line1"
    fi
    ver=$(echo "$stamp_line" | grep -oE 'v[0-9]+\.[0-9]+' | head -1)
    [ -z "$ver" ] && ver="(no stamp)"

    file_lines="${file_lines}"$'\n'"  ${fname}  ${ver}"

    if echo "$rel" | grep -q 'topoassist/' && echo "$GAS_NAMES" | grep -qw "$fname"; then
      gas_changed=1
      gas_project_dir=$(dirname "$full")
    fi
  done <<< "$uncommitted"

  [ -z "$file_lines" ] && exit 0

  # Auto-commit tracked changes (flock: prevent index.lock conflict with parallel sessions)
  exec 9>/tmp/claude-git.lock
  flock -x 9
  while IFS= read -r line; do
    [ -z "$line" ] && continue
    rel="${line:3}"
    git -C "$REPO" add -- "$REPO/$rel" 2>/dev/null
  done <<< "$uncommitted"

  git -C "$REPO" commit -m "chore: auto-commit session changes" >/dev/null 2>&1
  push_result=0
  git -C "$REPO" push >/dev/null 2>&1 || push_result=$?
  exec 9>&-   # release git lock before clasp

  REMOTE_URL=$(git -C "$REPO" remote get-url origin 2>/dev/null)
  REPO_NAME=$(echo "$REMOTE_URL" \
    | sed 's|https://github\.com/||;s|git@github\.com:||;s|\.git$||')
  [ -z "$REPO_NAME" ] && REPO_NAME="origin/main"

  if [ "$push_result" -eq 0 ]; then
    git_note="auto-committed + pushed to github.com/${REPO_NAME} ✓"
  else
    git_note="auto-committed but push FAILED — run: git push ✗"
  fi

  # Auto clasp push if GAS files changed
  clasp_label="GAS project"
  clasp_note="N/A (no GAS files changed)"
  if [ "$gas_changed" -eq 1 ] && [ -n "$gas_project_dir" ]; then
    if [ -f "$gas_project_dir/.clasp.json" ]; then
      script_id=$(jq -r '.scriptId // ""' "$gas_project_dir/.clasp.json" 2>/dev/null)
      script_name=$(basename "$gas_project_dir")
      short_id=$(echo "$script_id" | cut -c1-12)
      clasp_label="${script_name} [${short_id}...]"
    fi
    exec 8>/tmp/clasp-topoassist.lock
    flock -x 8
    push_out=$(cd "$gas_project_dir" && clasp push 2>&1)
    if echo "$push_out" | grep -q 'Pushed\|pushed'; then
      clasp_note="${clasp_label} auto-pushed ✓"
      date +%s > /tmp/topoassist_clasp_last_push
    else
      clasp_note="${clasp_label} push FAILED — run clasp push manually ✗"
    fi
    exec 8>&-   # release clasp lock
  fi

  SUMMARY="[AUTO-COMMITTED] session changes committed + pushed
Files:${file_lines}
Git:   ${git_note}
Clasp: ${clasp_note}"

  LOG="$HOME/claude/.change-log"
  echo "$SUMMARY" > "$LOG"
  echo "$SUMMARY" >&2
  jq -n --arg ctx "$SUMMARY" '{"systemMessage":$ctx}'
  exit 0
fi

# ── POSTTOOLUSEUSE:BASH MODE: fires on git commit/push or clasp push ──────────
# Only fire on relevant commands — strip quoted strings first to avoid false
# positives from commit messages containing "git push" etc.
cmd_unquoted=$(echo "$cmd" | sed 's/"[^"]*"//g; s/'"'"'[^'"'"']*'"'"'//g')
echo "$cmd_unquoted" | grep -qE 'git\s+(commit|push)|clasp\s+push' || exit 0

REPO="$HOME/claude"

# ── Repo name from remote URL ─────────────────────────────────────────────────
REMOTE_URL=$(git -C "$REPO" remote get-url origin 2>/dev/null)
REPO_NAME=$(echo "$REMOTE_URL" \
  | sed 's|https://github\.com/||;s|git@github\.com:||;s|\.git$||')
[ -z "$REPO_NAME" ] && REPO_NAME="origin/main"

# ── Last commit details ───────────────────────────────────────────────────────
COMMIT_HASH=$(git -C "$REPO" log -1 --format="%h" 2>/dev/null)
COMMIT_MSG=$(git -C "$REPO" log -1 --format="%s" 2>/dev/null | cut -c1-60)

# Skip noisy auto-commits generated by hooks (settings sync, session auto-commits)
echo "$COMMIT_MSG" | grep -qE '^(chore: auto-commit|settings: (auto-sync|sync external)|chore: update \.change-log)' && exit 0

# ── Determine which files to show ────────────────────────────────────────────
FILE_FILTER='CLAUDE\.md\|MEMORY\.md\|ROLLBACKS\.md\|\.template$'

if echo "$cmd_unquoted" | grep -qE 'git\s+push'; then
  prev_remote=$(git -C "$REPO" reflog show --format='%H' origin/main 2>/dev/null \
    | sed -n '2p')
  if [ -n "$prev_remote" ]; then
    CHANGED_FILES=$(git -C "$REPO" diff "$prev_remote"..HEAD --name-only 2>/dev/null \
      | grep -v "$FILE_FILTER")
  else
    CHANGED_FILES=$(git -C "$REPO" diff HEAD~1 HEAD --name-only 2>/dev/null \
      | grep -v "$FILE_FILTER")
  fi
else
  CHANGED_FILES=$(git -C "$REPO" diff HEAD~1 HEAD --name-only 2>/dev/null \
    | grep -v "$FILE_FILTER")
fi

# ── Extract version stamp from each changed file ──────────────────────────────
GAS_NAMES="Code.gs Sidebar.html Sidebar-js.html Sidebar-css.html SheetAssistPanel.html UserGuide.html Tests.gs"
file_lines=""
gas_changed=0
gas_project_dir=""

while IFS= read -r rel; do
  [ -z "$rel" ] && continue
  full="$REPO/$rel"
  fname=$(basename "$rel")
  [ -f "$full" ] || continue

  line1=$(head -1 "$full" 2>/dev/null)
  if echo "$line1" | grep -q '^#!'; then
    stamp_line=$(sed -n '2p' "$full" 2>/dev/null)
  else
    stamp_line="$line1"
  fi
  ver=$(echo "$stamp_line" | grep -oE 'v[0-9]+\.[0-9]+' | head -1)
  [ -z "$ver" ] && ver="(no stamp)"

  file_lines="${file_lines}"$'\n'"  ${fname}  ${ver}"

  if echo "$rel" | grep -q 'topoassist/' && echo "$GAS_NAMES" | grep -qw "$fname"; then
    gas_changed=1
    gas_project_dir=$(dirname "$full")
  fi
done <<< "$CHANGED_FILES"

[ -z "$file_lines" ] && exit 0

# ── Auto-push if git commit ran without git push ──────────────────────────────
unpushed=$(git -C "$REPO" log --oneline origin/main..HEAD 2>/dev/null | wc -l | tr -d ' ')
if echo "$cmd_unquoted" | grep -qE 'git\s+commit' && ! echo "$cmd_unquoted" | grep -qE 'git\s+push'; then
  if [ "$unpushed" -gt 0 ]; then
    exec 9>/tmp/claude-git.lock
    flock -x 9
    git -C "$REPO" push >/dev/null 2>&1 && unpushed=0
    exec 9>&-   # release git lock before clasp
  fi
fi

# ── Git push status ───────────────────────────────────────────────────────────
if echo "$cmd_unquoted" | grep -qE 'git\s+push' || [ "$unpushed" -eq 0 ]; then
  if [ "$unpushed" -eq 0 ]; then
    git_status="pushed to github.com/${REPO_NAME} ✓"
  else
    git_status="push to github.com/${REPO_NAME} FAILED — still ${unpushed} commit(s) ahead ✗"
  fi
else
  git_status="committed (not pushed — ${unpushed} ahead of github.com/${REPO_NAME})"
fi

# ── Clasp script info from .clasp.json ───────────────────────────────────────
clasp_label="GAS project"
if [ -n "$gas_project_dir" ] && [ -f "$gas_project_dir/.clasp.json" ]; then
  script_id=$(jq -r '.scriptId // ""' "$gas_project_dir/.clasp.json" 2>/dev/null)
  script_name=$(basename "$gas_project_dir")
  short_id=$(echo "$script_id" | cut -c1-12)
  clasp_label="${script_name} [${short_id}...]"
fi

# ── Clasp push status ─────────────────────────────────────────────────────────
CLASP_MARKER=/tmp/topoassist_clasp_last_push
if echo "$cmd_unquoted" | grep -qE 'clasp\s+push'; then
  clasp_status="${clasp_label} push ran ✓"
elif [ "$gas_changed" -eq 1 ]; then
  # All CLASP_MARKER reads, clasp push, and CLASP_MARKER writes under one lock
  exec 8>/tmp/clasp-topoassist.lock
  flock -x 8
  recently_pushed=0
  if [ -f "$CLASP_MARKER" ]; then
    last_push=$(cat "$CLASP_MARKER" 2>/dev/null)
    now=$(date +%s)
    age=$(( now - ${last_push:-0} ))
    if [ "$age" -lt 1800 ]; then
      pushed_at=$(date -d "@${last_push}" '+%H:%M:%S' 2>/dev/null \
        || date -r "${last_push}" '+%H:%M:%S' 2>/dev/null)
      clasp_status="${clasp_label} pushed by edit hook at ${pushed_at} ✓"
      recently_pushed=1
    fi
  fi
  # Not pushed recently — auto-push now
  if [ "$recently_pushed" -eq 0 ] && [ -n "$gas_project_dir" ]; then
    push_out=$(cd "$gas_project_dir" && clasp push 2>&1)
    if echo "$push_out" | grep -qi 'pushed\|push'; then
      clasp_status="${clasp_label} auto-pushed ✓"
      date +%s > "$CLASP_MARKER"
    else
      clasp_status="${clasp_label} auto-push FAILED — run clasp push manually ✗"
    fi
  fi
  exec 8>&-   # release clasp lock
else
  clasp_status="N/A (no GAS files changed)"
fi

# ── Build summary ─────────────────────────────────────────────────────────────
SUMMARY="[CHANGE SUMMARY] commit hash: ${COMMIT_HASH} — ${COMMIT_MSG}
Files:${file_lines}
Git:   ${git_status}
Clasp: ${clasp_status}"

LOG="$HOME/claude/.change-log"
echo "$SUMMARY" > "$LOG"

jq -n --arg ctx "$SUMMARY" '{"systemMessage":$ctx}'
