# Save this file to trigger 'Dark' logic for the toggle
setw -g window-active-style fg=colour250,bg=colour235
setw -g window-style fg=colour245,bg=colour236
set -g pane-border-style fg=colour237,bg=colour234
set -g pane-active-border-style fg=green,bg=colour234

set -g status-style "bg=colour234,fg=green"
setw -g window-status-current-style bg=colour234,fg=white,bold
setw -g window-status-style bg=colour234,fg=green

# Marker for toggle logic
run-shell "echo 'bg=dark' > ~/.tmux/themes/current_theme.conf"
