# Save this file to trigger 'Light' logic for the toggle
setw -g window-active-style fg=terminal,bg=terminal
setw -g window-style fg=colour240,bg=colour254
set -g pane-border-style fg=colour250,bg=white
set -g pane-active-border-style fg=black,bg=white

set -g status-style "bg=white,fg=blue"
setw -g window-status-current-style bg=white,fg=black
setw -g window-status-style bg=white,fg=blue

# Marker for toggle logic
run-shell "echo 'bg=white' > ~/.tmux/themes/current_theme.conf"
