# tmux.conf v260506.4 | 2026-05-06 17:08:24
# Save this file to trigger 'Light' logic for the toggle
setw -g window-active-style fg=terminal,bg=terminal
setw -g window-style fg=terminal,bg=terminal
set -g pane-border-style fg=colour250
set -g pane-active-border-style fg=colour39,bold

set -g status-style "bg=colour253,fg=blue"
setw -g window-status-current-style bg=colour253,fg=black
setw -g window-status-style bg=colour253,fg=blue

# Marker for toggle logic
run-shell "echo 'bg=white' > ~/.tmux/themes/current_theme.conf"
